version: '3.9'

services:
  firebase:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: uplim/triplate-firebase
    container_name: triplate-anonymous
    environment:
      FIRESTORE_EMULATOR_HOST: localhost:8080
      FIREBASE_STORAGE_EMULATOR_HOST: localhost:9199
      FIREBASE_AUTH_EMULATOR_HOST: localhost:9099
    tty: true
    ports:
      - 4000:4000 # Emulator Suite UI
      - 8080:8080 # Cloud Firestore
      - 9099:9099 # Firebase Authentication
      - 9199:9199 # Cloud Storage
    volumes:
      - ./node:/home/node
