version: '3.9'

services:
  front:
    build:
      context: ../../
      dockerfile: dev/frontend/Dockerfile
    image: uplim/triplate
    container_name: triplate
    tty: true
    ports:
      - 3000:3000 # Next.js
      - 3001:3001 # Wiki
      - 6006:6006 # Storybook
    volumes:
      - .:/works
      - node_modules:/works/node_modules:delegated
      - build_volume:/works/.next:nocopy

volumes:
  node_modules_front:
    name: triplate-node-modules-front
