# https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-react-and-next

name: CI

on:
  push:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.11.1
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'

      - name: Create dot env file
        run: |
          cat > .env <<EOF
          TZ=Asia/Tokyo
          FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_ADMIN_CLIENT_EMAIL=${{ secrets.FIREBASE_ADMIN_CLIENT_EMAIL }}
          FIREBASE_ADMIN_PRIVATE_KEY=${{ secrets.FIREBASE_ADMIN_PRIVATE_KEY }}
          EOF

      - name: Monorepo install
        uses: ./.github/actions/yarn-nm-install
        with:
          cwd: '.'
          enable-corepack: true
          cache-node-modules: true
          cache-install-state: true

      - name: Lint and Type Check
        run: |
          yarn ci
          yarn type-check
          yarn workspace wiki markdownlint

      - name: Check Build
        run: yarn build
