name: deploy

on:
  push:
    branches:
      - main
    paths:
      - wiki/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - run: vercel --yes --prod --token=${{ secrets.VERCEL_ACCESS_TOKEN }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_WIKI_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
