name: 'VRT'

on:
  push:
    paths:
    - src/**/*.tsx
    - src/**/*.ts
  workflow_dispatch:

jobs:
  vrt:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Build image
        run: docker compose -f ./dev/vrt/docker-compose.yml build

      - name: Run vrt
        run: docker compose -f ./dev/vrt/docker-compose.yml run --rm vrt yarn playwright test tests/vrt --project=chromium
